export const ROUTES = Object.freeze({
    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    FORGET_PASSWORD: 'FORGET_PASSWORD',
    ERROR: 'ERROR',
    CONFIRM_EMAIL: 'CONFIRM_EMAIL',
    RESET_PASSWORD: 'RESET_PASSWORD',

    HOME: 'HOME',
    SEARCH: 'SEARCH',
    LIBRARY: 'LIBRARY',
    DETAIL: 'DETAIL',
    NEW_RELEASE: 'NEW_RELEASE',
    SETTING: 'SETTING',
    PROFILE: 'PROFILE',
    PLAYER: 'PLAYER'
});
